2021-09-10 12:04:14,029 INFO    MainThread:6512 [internal.py:wandb_internal():86] W&B internal server running at pid: 6512, started at: 2021-09-10 12:04:14.020167
2021-09-10 12:04:14,036 INFO    WriterThread:6512 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210910_120412-1cj9z0j0\run-1cj9z0j0.wandb
2021-09-10 12:04:14,036 DEBUG   HandlerThread:6512 [handler.py:handle_request():126] handle_request: run_start
2021-09-10 12:04:14,055 DEBUG   HandlerThread:6512 [meta.py:__init__():40] meta init
2021-09-10 12:04:14,055 DEBUG   HandlerThread:6512 [meta.py:__init__():54] meta init done
2021-09-10 12:04:14,055 DEBUG   HandlerThread:6512 [meta.py:probe():211] probe
2021-09-10 12:04:14,135 DEBUG   HandlerThread:6512 [git.py:repo():33] git repository is invalid
2021-09-10 12:04:14,135 DEBUG   HandlerThread:6512 [meta.py:_save_pip():58] save pip
2021-09-10 12:04:14,136 DEBUG   HandlerThread:6512 [meta.py:_save_pip():72] save pip done
2021-09-10 12:04:14,137 DEBUG   HandlerThread:6512 [meta.py:probe():249] probe done
