2021-09-10 11:26:20,796 INFO    MainThread:2416 [internal.py:wandb_internal():86] W&B internal server running at pid: 2416, started at: 2021-09-10 11:26:20.787288
2021-09-10 11:26:20,803 INFO    WriterThread:2416 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210910_112619-1wfb7boi\run-1wfb7boi.wandb
2021-09-10 11:26:20,803 DEBUG   HandlerThread:2416 [handler.py:handle_request():126] handle_request: run_start
2021-09-10 11:26:20,828 DEBUG   HandlerThread:2416 [meta.py:__init__():40] meta init
2021-09-10 11:26:20,829 DEBUG   HandlerThread:2416 [meta.py:__init__():54] meta init done
2021-09-10 11:26:20,829 DEBUG   HandlerThread:2416 [meta.py:probe():211] probe
2021-09-10 11:26:20,903 DEBUG   HandlerThread:2416 [git.py:repo():33] git repository is invalid
2021-09-10 11:26:20,903 DEBUG   HandlerThread:2416 [meta.py:_save_pip():58] save pip
2021-09-10 11:26:20,904 DEBUG   HandlerThread:2416 [meta.py:_save_pip():72] save pip done
2021-09-10 11:26:20,905 DEBUG   HandlerThread:2416 [meta.py:probe():249] probe done
