

























































38787it [02:23, 256.79it/s]Traceback (most recent call last):
  File "c:\Programming\rl_cooperation\DQN_breakout_gpu\agent.PY", line 177, in main
    observation, reward, done, info = env.step(action)
  File "c:\Programming\rl_cooperation\DQN_breakout_gpu\utils.py", line 27, in step
    image, reward, done,  info = self.env.step(action)
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\wrappers\time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\atari\atari_env.py", line 121, in step
    ob = self._get_obs()
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\atari\atari_env.py", line 139, in _get_obs
    img = self._get_image()
  File "C:\Programming\rl_cooperation\lib\site-packages\gym\envs\atari\atari_env.py", line 126, in _get_image
    return self.ale.getScreenRGB2()
  File "C:\Programming\rl_cooperation\lib\site-packages\atari_py\ale_python_interface.py", line 266, in getScreenRGB2
    ale_lib.getScreenRGB2(self.obj, as_ctypes(screen_data[:]))
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\ctypeslib.py", line 535, in as_ctypes
    ctype_scalar = as_ctypes_type(ai["typestr"])
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\ctypeslib.py", line 497, in as_ctypes_type
    return _ctype_from_dtype(_dtype(dtype))
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\ctypeslib.py", line 456, in _ctype_from_dtype
    return _ctype_from_dtype_scalar(dtype)
  File "C:\Programming\rl_cooperation\lib\site-packages\numpy\ctypeslib.py", line 373, in _ctype_from_dtype_scalar
    dtype_with_endian = dtype.newbyteorder('S').newbyteorder('S')
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\Programming\rl_cooperation\DQN_breakout_gpu\agent.PY", line 242, in <module>
    main(False)
  File "c:\Programming\rl_cooperation\DQN_breakout_gpu\agent.PY", line 239, in main
    env.close()
AttributeError: 'FramestackingENV' object has no attribute 'close'