2021-09-10 11:29:41,792 INFO    MainThread:9344 [internal.py:wandb_internal():86] W&B internal server running at pid: 9344, started at: 2021-09-10 11:29:41.783933
2021-09-10 11:29:41,799 INFO    WriterThread:9344 [datastore.py:open_for_write():77] open: C:\Programming\rl_cooperation\Pygame_RL_cooperation\wandb\offline-run-20210910_112940-1ss2e2mq\run-1ss2e2mq.wandb
2021-09-10 11:29:41,799 DEBUG   HandlerThread:9344 [handler.py:handle_request():126] handle_request: run_start
2021-09-10 11:29:41,817 DEBUG   HandlerThread:9344 [meta.py:__init__():40] meta init
2021-09-10 11:29:41,818 DEBUG   HandlerThread:9344 [meta.py:__init__():54] meta init done
2021-09-10 11:29:41,818 DEBUG   HandlerThread:9344 [meta.py:probe():211] probe
2021-09-10 11:29:41,898 DEBUG   HandlerThread:9344 [git.py:repo():33] git repository is invalid
2021-09-10 11:29:41,898 DEBUG   HandlerThread:9344 [meta.py:_save_pip():58] save pip
2021-09-10 11:29:41,900 DEBUG   HandlerThread:9344 [meta.py:_save_pip():72] save pip done
2021-09-10 11:29:41,900 DEBUG   HandlerThread:9344 [meta.py:probe():249] probe done
