2021-09-01 13:56:35,226 INFO    MainThread:36332 [wandb_setup.py:_flush():69] setting env: {}
2021-09-01 13:56:35,227 INFO    MainThread:36332 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-01 13:56:35,227 INFO    MainThread:36332 [wandb_init.py:_log_setup():342] Logging user logs to C:\Programming\rl_cooperation\DQN_SpaceCannons\wandb\run-20210901_135635-rrpa2m4r\logs\debug.log
2021-09-01 13:56:35,228 INFO    MainThread:36332 [wandb_init.py:_log_setup():343] Logging internal logs to C:\Programming\rl_cooperation\DQN_SpaceCannons\wandb\run-20210901_135635-rrpa2m4r\logs\debug-internal.log
2021-09-01 13:56:35,228 INFO    MainThread:36332 [wandb_init.py:init():375] calling init triggers
2021-09-01 13:56:35,228 INFO    MainThread:36332 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-01 13:56:35,229 INFO    MainThread:36332 [wandb_init.py:init():424] starting backend
2021-09-01 13:56:35,229 INFO    MainThread:36332 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-01 13:56:35,235 INFO    MainThread:36332 [backend.py:ensure_launched():135] starting backend process...
2021-09-01 13:56:35,326 INFO    MainThread:36332 [backend.py:ensure_launched():139] started backend process with pid: 28660
2021-09-01 13:56:35,326 INFO    MainThread:36332 [wandb_init.py:init():429] backend started and connected
2021-09-01 13:56:35,327 INFO    MainThread:36332 [wandb_init.py:init():477] updated telemetry
2021-09-01 13:56:35,327 INFO    MainThread:36332 [wandb_init.py:init():500] communicating current version
2021-09-01 13:56:36,486 INFO    MainThread:36332 [wandb_init.py:init():505] got version response 
2021-09-01 13:56:36,487 INFO    MainThread:36332 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-01 13:56:36,687 INFO    MainThread:36332 [wandb_init.py:init():540] starting run threads in backend
2021-09-01 13:56:36,868 INFO    MainThread:36332 [wandb_run.py:_console_start():1601] atexit reg
2021-09-01 13:56:36,869 INFO    MainThread:36332 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-01 13:56:36,869 INFO    MainThread:36332 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-01 13:56:36,872 INFO    MainThread:36332 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-01 13:56:36,872 INFO    MainThread:36332 [wandb_init.py:init():565] run started, returning control to user process
2021-09-01 13:56:38,414 INFO    MainThread:36332 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 1
2021-09-01 13:56:38,414 INFO    MainThread:36332 [wandb_run.py:_restore():1543] restore
2021-09-01 13:56:39,282 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 562
  total_bytes: 562
}

2021-09-01 13:56:39,553 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 562
  total_bytes: 562
}

2021-09-01 13:56:39,718 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 562
  total_bytes: 4324
}

2021-09-01 13:56:39,834 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 562
  total_bytes: 4350
}

2021-09-01 13:56:39,940 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,050 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,159 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,268 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,377 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,486 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,812 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:40,919 INFO    MainThread:36332 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4350
  total_bytes: 4350
}

2021-09-01 13:56:42,080 INFO    MainThread:36332 [wandb_run.py:_show_files():1915] logging synced files
